### PR TITLE
SLING-7452 Document the handling of multiple value fields with SlingPostServlet

### PR DESCRIPTION
**Pull request by dplaton**
Please review and merge accordingly.

Thank you.

### CODE REVIEW

**Comment by dplaton** [comment]
I see that the changes are already documented at http://sling.apache.org/documentation/bundles/manipulating-content-the-slingpostservlet-servlets-post.html#patch

Wouldn't make sense to have this at least moved in the "Multiple values" section?

**Comment by rombert** [comment]
@dplaton - would it work if you added a link from the 'multiple values' section to the 'patch' section? Also it would be good to review if your changes have any additions/clarifications over the current docs.

**Comment by dplaton** [comment]
Ok @rombert , I added a link to the 'patch' section. That section covers everything there is to know.

**Comment by rombert** [comment]
I know I'm nitpicking, but there's already an auto-generated patch anchor - https://sling.apache.org/documentation/bundles/manipulating-content-the-slingpostservlet-servlets-post.html#patch . Can you use that instead?

**Comment by dplaton** [comment]
Ok, I wanted to use an internal link instead of the long one.

**Comment by rombert** [comment]
Can't you use '#patch' as a link?

**Comment by rombert** [comment]
It's auto-generated by the markdown template, so the editor can't know about it.

**Comment by rombert** [comment]
Looks good, thanks!

**Pull request closed without merging**
