### PR TITLE
SLING-11204 enable web analytics with ASF Matomo

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
Unfortunately I cannot try it out locally due to https://github.com/jbake-org/jbake/issues/709.

**Comment by rombert** [comment]
FWIW the build fails locally for me as well.

**Comment by rombert** [comment]
LGTM on a local test.

**Review by bdelacretaz — APPROVED** [review]
Works for me on a local build and I see a POST request to https://matomo.privacy.apache.org/matomo.php with a 204 response.

**Pull request merged**
